### ISSUE TITLE
Reporte de practica del diseño de la estructura de la librería DLL

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-equipo-j-a-k#1]
[REPORTE_PARACTICA_2_Diseño_de_estructura_de_libreria_DLL.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-equipo-j-a-k/files/14725172/REPORTE_PARACTICA_2_Diseno_de_estructura_de_libreria_DLL.pdf)

**Comment by EdgarExa** [comment]
20% de 20 bien hecho

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
