### ISSUE TITLE
Reporte de creación de una librería 

### ISSUE THREAD

**Issue by EdgarExa** [SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-equipo-j-a-k#2]
[reporte.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-equipo-j-a-k/files/14734346/reporte.pdf)

**Comment by Jaczibeth** [comment]
al trabajo presentado le damos un 16 de 20 , ya que el reporte se presenta de manera desordena y no trae algunas cosas que se dice en la rubrica.

**Comment by josealfredo79** [comment]
esta bien...
